# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateBulkTicketsOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stop_on_error': 'bool'
    }

    attribute_map = {
        'stop_on_error': 'stopOnError'
    }

    def __init__(self, stop_on_error=None):  # noqa: E501
        """CreateBulkTicketsOptions - a model defined in Swagger"""  # noqa: E501
        self._stop_on_error = None
        self.discriminator = None
        if stop_on_error is not None:
            self.stop_on_error = stop_on_error

    @property
    def stop_on_error(self):
        """Gets the stop_on_error of this CreateBulkTicketsOptions.  # noqa: E501

        Whether to stop on error  # noqa: E501

        :return: The stop_on_error of this CreateBulkTicketsOptions.  # noqa: E501
        :rtype: bool
        """
        return self._stop_on_error

    @stop_on_error.setter
    def stop_on_error(self, stop_on_error):
        """Sets the stop_on_error of this CreateBulkTicketsOptions.

        Whether to stop on error  # noqa: E501

        :param stop_on_error: The stop_on_error of this CreateBulkTicketsOptions.  # noqa: E501
        :type: bool
        """

        self._stop_on_error = stop_on_error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateBulkTicketsOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBulkTicketsOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
