import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_b94bf2f654(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_5d1b1efdca():spartaqube_cli.list()
@app.command()
def sparta_50f1ceecd0():spartaqube_cli.sparta_50f1ceecd0()
@app.command()
def sparta_65bdec0596():print('Hello world!')
if __name__=='__main__':app()