import typing
import collections.abc
import typing_extensions

class FunctionStore: ...

class ReturnStore:
    """tuple() -> empty tuple
    tuple(iterable) -> tuple initialized from iterable's itemsIf the argument is a tuple, the return value is the same object.
    """

def fromxml(data): ...
def tag_module(mod_name, tags): ...
def tag_vars(tags, module="bpyml"): ...
def topretty_py(py_data, indent="    "): ...
def toxml(py_data, indent="    "): ...
