# coding: utf-8

"""
    Enyday API

    API for Enyday energy services integration

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from enyday.models.nordpool_average import NordpoolAverage

class TestNordpoolAverage(unittest.TestCase):
    """NordpoolAverage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NordpoolAverage:
        """Test NordpoolAverage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NordpoolAverage`
        """
        model = NordpoolAverage()
        if include_optional:
            return NordpoolAverage(
                delivery_area = '',
                status = '',
                currency = '',
                value = 1.337,
                start_time = ''
            )
        else:
            return NordpoolAverage(
        )
        """

    def testNordpoolAverage(self):
        """Test NordpoolAverage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
