from .Decision_Tree import DecisionTree
from .Knearest import knn
from .Linear_regression import LinearRegression
from .Multiple_regression import MultipleLinearRegression
from .Random_forest import RandomForest
from .Support_vector import svm
from .XGBoost import xgBoost
from .Logistic_regression import LogisticRegression
from .Decision_Tree_Reg import DecisionTreeRegression