# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_update_tags_response_data import AllOfUpdateTagsResponseData  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfUpdateTagsResponseData(unittest.TestCase):
    """AllOfUpdateTagsResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfUpdateTagsResponseData(self):
        """Test AllOfUpdateTagsResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_update_tags_response_data.AllOfUpdateTagsResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
