# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mark_duplicate_body import MarkDuplicateBody  # noqa: E501
from swagger_client.rest import ApiException


class TestMarkDuplicateBody(unittest.TestCase):
    """MarkDuplicateBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarkDuplicateBody(self):
        """Test MarkDuplicateBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mark_duplicate_body.MarkDuplicateBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
