# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.team_member_response_dto import TeamMemberResponseDto  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamMemberResponseDto(unittest.TestCase):
    """TeamMemberResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamMemberResponseDto(self):
        """Test TeamMemberResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.team_member_response_dto.TeamMemberResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
