# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_create_ticket_tags_response_data import AllOfCreateTicketTagsResponseData  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfCreateTicketTagsResponseData(unittest.TestCase):
    """AllOfCreateTicketTagsResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfCreateTicketTagsResponseData(self):
        """Test AllOfCreateTicketTagsResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_create_ticket_tags_response_data.AllOfCreateTicketTagsResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
