# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_draft_ticket_dto import UpdateDraftTicketDto  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateDraftTicketDto(unittest.TestCase):
    """UpdateDraftTicketDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDraftTicketDto(self):
        """Test UpdateDraftTicketDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_draft_ticket_dto.UpdateDraftTicketDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
