# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .pipeline_file_create_custom_metadata_value import PipelineFileCreateCustomMetadataValue
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class PipelineFileCreate(UniversalBaseModel):
    """
    Schema for creating a file that is associated with a pipeline.
    """

    file_id: str = pydantic.Field()
    """
    The ID of the file
    """

    custom_metadata: typing.Optional[typing.Dict[str, typing.Optional[PipelineFileCreateCustomMetadataValue]]] = (
        pydantic.Field(default=None)
    )
    """
    Custom metadata for the file
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
