# make_partially_linear_dataset_constant { #caml.extensions.synthetic_data.make_partially_linear_dataset_constant }

```python
make_partially_linear_dataset_constant(
    n_obs=1000,
    ate=4.0,
    n_confounders=10,
    dgp='make_plr_CCDDHNR2018',
    seed=None,
    **doubleml_kwargs,
)
```

Simulate a data generating process from a partially linear model with a constant treatment effect (ATE only).

The outcome and treatment are both continuous.The dataset is generated using the `make_plr_CCDDHNR2018` or `make_plr_turrell2018` function from the [`doubleml` package](https://docs.doubleml.org/stable/index.html).

The general form of the data generating process is:

$$
y_i= \tau_0 d_i + g(\mathbf{W_i})+\epsilon_i
$$
$$
d_i=f(\mathbf{W_i})+\eta_i
$$

where $y_i$ is the outcome, $d_i$ is the treatment, $\mathbf{W_i}$ are the confounders, $\epsilon_i$ and $\eta_i$ are the error terms, $\tau_0$ is the ATE parameter, $g$ is the outcome function, and $f$ is the treatment function.

See the `doubleml` documentation for more details on the specific functional forms of the data generating process.

As a DAG, the data generating process can be roughly represented as:

<div style="text-align: center;">
```{mermaid}
flowchart TD;
    W((W))-->d((d));
    W((W))-->y((y));
    d((d))-->|"τ0"|y((y));
    linkStyle 0,1 stroke:black,stroke-width:2px
    linkStyle 1,2 stroke:black,stroke-width:2px
```
</div>

## Parameters {.doc-section .doc-section-parameters}

| Name              | Type        | Description                                                                                | Default                  |
|-------------------|-------------|--------------------------------------------------------------------------------------------|--------------------------|
| n_obs             | int         | The number of observations to generate.                                                    | `1000`                   |
| ate               | float       | The average treatment effect $\tau_0$.                                                     | `4.0`                    |
| n_confounders     | int         | The number of confounders $\mathbf{W_i}$ to generate.                                      | `10`                     |
| dgp               | str         | The data generating process to use. Can be "make_plr_CCDDHNR20" or "make_plr_turrell2018". | `'make_plr_CCDDHNR2018'` |
| seed              | int \| None | The seed to use for the random number generator.                                           | `None`                   |
| **doubleml_kwargs |             | Additional keyword arguments to pass to the data generating process.                       | `{}`                     |

## Returns {.doc-section .doc-section-returns}

| Name       | Type             | Description                                                                                  |
|------------|------------------|----------------------------------------------------------------------------------------------|
| df         | pandas.DataFrame | The generated dataset where y is the outcome, d is the treatment, and W are the confounders. |
| true_cates | numpy.ndarray    | The true conditional average treatment effects, which are all equal to the ATE here.         |
| true_ate   | float            | The true average treatment effect.                                                           |

## Examples {.doc-section .doc-section-examples}

```{python}
from caml.extensions.synthetic_data import make_partially_linear_dataset_constant
df, true_cates, true_ate = make_partially_linear_dataset_constant(n_obs=1000,
                                                    ate=4.0,
                                                    n_confounders=10,
                                                    dgp="make_plr_CCDDHNR2018",
                                                    seed=1)

print(f"True CATES: {true_cates[:5]}")
print(f"True ATE: {true_ate}")
print(df.head())
```