key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIFaMupPGfs4HeNqeO79cQ/T8oFhOW9XpJAOy7oc247DnoAoGCCqGSM49
AwEHoUQDQgAESBT3HZWk/z7G0RWKULAbhYW3QEu6LWz8Js3N9vWefgEJSrSlSHw+
uM06lbX+d6xXWFS0hkAYNP2IpsUyHEEFkg==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6jCCAY8CFHEG4hrPag+DbRaGd+PG27opXSxKMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTAyMDMwODIyMzRaFw0zNTAyMDEwODIy
MzRaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABEgU9x2VpP8+xtEVilCwG4WFt0BLui1s/CbNzfb1nn4BCUq0pUh8PrjN
OpW1/nesV1hUtIZAGDT9iKbFMhxBBZIwCgYIKoZIzj0EAwIDSQAwRgIhAINzsXQz
RAF1+F8ECSP3fyPH4FUw32kzoKRA5V0iR6uXAiEAwevGdpqmUIKRLGgAT/N/iZdi
RkBaBNzGzP0yguxa5rg=
-----END CERTIFICATE-----
"""