from setuptools import setup, find_packages

setup(
    name='azdatalake',
    version='1.1.0',
    description='A package to implement a singleton for azure data storage gen2',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Alan Medina',
    author_email='amedina.escom@hotmail.com',
    url='https://github.com/amedinag32/azdatalake',
    packages=find_packages(),
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.8',
    install_requires=[
        "azure-core==1.32.0",
        "azure-storage-queue==12.12.0",
        "certifi==2024.12.14",
        "cffi==1.17.1",
        "charset-normalizer==3.4.0",
        "cryptography==44.0.0",
        "greenlet==3.1.1",
        "idna==3.10",
        "isodate==0.7.2",
        "numpy==1.24.4",
        "pandas==2.0.3",
        "pandasql==0.7.3",
        "pycparser==2.22",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.2",
        "requests==2.32.3",
        "six==1.17.0",
        "typing-extensions==4.12.2",
        "tzdata==2024.2",
        "urllib3==2.2.3",
    ],
)
