__title__ = "pyemias"
__description__ = "pyemias"
__url__ = "https://github.com/GvozdevAD/pyemias"
__version__ = "0.0.3"
__author__ = "GvozdevAD"
__author_email__ = "alexander@gvozdev.net"
__license__ = "MIT License"