from typing import Any, TypeVar

__all__ = ['requireNotNull', 'isNumber', 'toInt', 'toFloat', 'asList', 'keysAsList']

T = TypeVar('T')

def requireNotNull(obj: T | None) -> T: ...
def isNumber(anyVal: Any) -> bool: ...
def toInt(val: Any) -> int: ...
def toFloat(val: Any) -> float: ...
def asList(dct: dict[Any, T]) -> list[T]: ...
def keysAsList(dct: dict[T, Any]) -> list[T]: ...
