from deepdiff import DeepDiff

# main_property_map = {'oven_type': {'type': 'string', 'r': ['COMBI'], 'w': []}, 'notification': {'push': ['TIME_TO_CLEAN', 'PREHEATING_IS_COMPLETE', 'COOKING_IS_COMPLETE', 'ERROR_HAS_OCCURRED']}}
# upper_property_map = {'current_state': {'type': 'enum', 'r': ['DONE', 'CLEANING', 'COOLING', 'PREHEATING', 'COOKING_IN_PROGRESS', 'CLEANING_IS_DONE', 'INITIAL'], 'w': []}, 'target_temperature_c': {'type': 'number', 'r': True, 'w': False}, 'target_temperature_f': {'type': 'number', 'r': True, 'w': False}, 'remain_minute': {'type': 'number', 'r': True, 'w': False}, 'remain_second': {'type': 'number', 'r': True, 'w': False}, 'remain_hour': {'type': 'number', 'r': True, 'w': False}, 'notification': {'push': ['TIME_TO_CLEAN', 'PREHEATING_IS_COMPLETE', 'COOKING_IS_COMPLETE', 'ERROR_HAS_OCCURRED']}}
# lower_property_map = {'current_state': {'type': 'enum', 'r': ['DONE', 'CLEANING', 'COOLING', 'PREHEATING', 'COOKING_IN_PROGRESS', 'CLEANING_IS_DONE', 'INITIAL'], 'w': []}, 'oven_operation_mode': {'type': 'enum', 'r': [], 'w': ['PREHEATING', 'START', 'STOP']}, 'cook_mode': {'type': 'enum', 'r': ['BAKE', 'ROAST', 'CONVECTION_BAKE', 'CONVECTION_ROAST', 'CRISP_CONVECTION', 'OTHERS'], 'w': ['BAKE', 'CONVECTION_BAKE', 'CONVECTION_ROAST']}, 'remote_control_enabled': {'type': 'boolean', 'r': True, 'w': False}, 'target_temperature_c': {'type': 'range', 'r': {'min': 80, 'max': 285, 'step': 1}, 'w': {'min': 80, 'max': 285, 'step': 1}, 'unit': 'C'}, 'target_temperature_f': {'type': 'range', 'r': {'min': 170, 'max': 550, 'step': 1}, 'w': {'min': 170, 'max': 550, 'step': 1}, 'unit': 'F'}, 'timer_minute': {'type': 'number', 'r': False, 'w': True}, 'timer_hour': {'type': 'number', 'r': False, 'w': True}, 'remain_minute': {'type': 'number', 'r': True, 'w': False}, 'remain_hour': {'type': 'number', 'r': True, 'w': False}, 'target_minute': {'type': 'number', 'r': False, 'w': True}, 'target_hour': {'type': 'number', 'r': False, 'w': True}, 'remain_second': {'type': 'number', 'r': True, 'w': False}, 'notification': {'push': ['TIME_TO_CLEAN', 'PREHEATING_IS_COMPLETE', 'COOKING_IS_COMPLETE', 'ERROR_HAS_OCCURRED']}}
# device_property_map = {'_': {'oven_type': {'type': 'string', 'r': ['COMBI'], 'w': []}, 'notification':
#     {'type': 'enum', 'r': ['TIME_TO_CLEAN', 'PREHEATING_IS_COMPLETE', 'COOKING_IS_COMPLETE', 'ERROR_HAS_OCCURRED']}},
#                        'upper': {'current_state': {'type': 'enum', 'r': ['DONE', 'CLEANING', 'COOLING', 'PREHEATING', 'COOKING_IN_PROGRESS', 'CLEANING_IS_DONE', 'INITIAL'], 'w': []}, 'target_temperature_c': {'type': 'number', 'r': True, 'w': False}, 'target_temperature_f': {'type': 'number', 'r': True, 'w': False}, 'remain_minute': {'type': 'number', 'r': True, 'w': False}, 'remain_second': {'type': 'number', 'r': True, 'w': False}, 'remain_hour': {'type': 'number', 'r': True, 'w': False}}, 'lower': {'current_state': {'type': 'enum', 'r': ['DONE', 'CLEANING', 'COOLING', 'PREHEATING', 'COOKING_IN_PROGRESS', 'CLEANING_IS_DONE', 'INITIAL'], 'w': []}, 'oven_operation_mode': {'type': 'enum', 'r': [], 'w': ['PREHEATING', 'START', 'STOP']}, 'cook_mode': {'type': 'enum', 'r': ['BAKE', 'ROAST', 'CONVECTION_BAKE', 'CONVECTION_ROAST', 'CRISP_CONVECTION', 'OTHERS'], 'w': ['BAKE', 'CONVECTION_BAKE', 'CONVECTION_ROAST']}, 'remote_control_enabled': {'type': 'boolean', 'r': True, 'w': False}, 'target_temperature_c': {'type': 'range', 'r': {'min': 80, 'max': 285, 'step': 1}, 'w': {'min': 80, 'max': 285, 'step': 1}, 'unit': 'C'}, 'target_temperature_f': {'type': 'range', 'r': {'min': 170, 'max': 550, 'step': 1}, 'w': {'min': 170, 'max': 550, 'step': 1}, 'unit': 'F'}, 'timer_minute': {'type': 'number', 'r': False, 'w': True}, 'timer_hour': {'type': 'number', 'r': False, 'w': True}, 'remain_minute': {'type': 'number', 'r': True, 'w': False}, 'remain_hour': {'type': 'number', 'r': True, 'w': False}, 'target_minute': {'type': 'number', 'r': False, 'w': True}, 'target_hour': {'type': 'number', 'r': False, 'w': True}, 'remain_second': {'type': 'number', 'r': True, 'w': False}}}


# compare_property_map = {
#     "_": main_property_map,
#     "upper": upper_property_map,
#     "lower": lower_property_map,
# }


compare_property_map = {
    "_": {'notification': {'push': ['WASHING_IS_COMPLETE', 'ERROR_DURING_WASHING']}},
    "main": {'current_state': {'type': 'enum', 'r': ['DISPLAY_LOADSIZE', 'DRYING', 'REFRESHING', 'INITIAL', 'SPINNING', 'PROOFING', 'RUNNING', 'RESERVED', 'COOL_DOWN', 'PAUSE', 'POWER_OFF', 'STEAM_SOFTENING', 'RINSE_HOLD', 'CHANGE_CONDITION', 'ERROR', 'CHECKING_TURBIDITY', 'DETERGENT_AMOUNT', 'DETECTING', 'SLEEP', 'DISPENSING', 'RINSING', 'SOFTENING', 'FIRMWARE', 'PREWASH', 'END'], 'w': []}, 'washer_operation_mode': {'type': 'enum', 'r': [], 'w': ['START', 'STOP', 'POWER_OFF', 'WAKE_UP']}, 'remote_control_enabled': {'type': 'boolean', 'r': True, 'w': False}, 'remain_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'relative_minute_to_stop': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'total_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'relative_hour_to_stop': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {'max': 30, 'min': 0, 'step': 1, 'except': []}}, 'total_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'remain_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'detergent_setting': {'type': 'string', 'r': ['NORMAL'], 'w': []}, 'notification': {'push': ['WASHING_IS_COMPLETE', 'ERROR_DURING_WASHING']}, 
             'errors': ['TEMPERATURE_SENSOR_ERROR', 'DOOR_OPEN_ERROR', 'WATER_DRAIN_ERROR', 'UNABLE_TO_LOCK_ERROR', 'OVERFILL_ERROR', 'OUT_OF_BALANCE_ERROR', 'WATER_SUPPLY_ERROR', 'WATER_LEVEL_SENSOR_ERROR', 'LOCKED_MOTOR_ERROR']},
    "mini": {'current_state': {'type': 'enum', 'r': ['DISPLAY_LOADSIZE', 'DRYING', 'REFRESHING', 'INITIAL', 'SPINNING', 'PROOFING', 'RUNNING', 'RESERVED', 'COOL_DOWN', 'PAUSE', 'POWER_OFF', 'STEAM_SOFTENING', 'RINSE_HOLD', 'CHANGE_CONDITION', 'ERROR', 'CHECKING_TURBIDITY', 'DETERGENT_AMOUNT', 'DETECTING', 'SLEEP', 'DISPENSING', 'RINSING', 'SOFTENING', 'FIRMWARE', 'PREWASH', 'END'], 'w': []}, 'washer_operation_mode': {'type': 'enum', 'r': [], 'w': ['START', 'STOP', 'POWER_OFF']}, 'remote_control_enabled': {'type': 'boolean', 'r': True, 'w': False}, 'total_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'remain_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'total_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'remain_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'notification': {'push': ['WASHING_IS_COMPLETE', 'ERROR_DURING_WASHING']}, 'errors': ['TEMPERATURE_SENSOR_ERROR', 'DOOR_OPEN_ERROR', 'WATER_DRAIN_ERROR', 'UNABLE_TO_LOCK_ERROR', 'OVERFILL_ERROR', 'OUT_OF_BALANCE_ERROR', 'WATER_SUPPLY_ERROR', 'WATER_LEVEL_SENSOR_ERROR', 'LOCKED_MOTOR_ERROR']},
}

device_property_map = {'_': {'notification': {'type': 'enum', 'r': ['WASHING_IS_COMPLETE', 'ERROR_DURING_WASHING']}}, 'main': {'current_state': {'type': 'enum', 'r': ['DISPLAY_LOADSIZE', 'DRYING', 'REFRESHING', 'INITIAL', 'SPINNING', 'PROOFING', 'RUNNING', 'RESERVED', 'COOL_DOWN', 'PAUSE', 'POWER_OFF', 'STEAM_SOFTENING', 'RINSE_HOLD', 'CHANGE_CONDITION', 'ERROR', 'CHECKING_TURBIDITY', 'DETERGENT_AMOUNT', 'DETECTING', 'SLEEP', 'DISPENSING', 'RINSING', 'SOFTENING', 'FIRMWARE', 'PREWASH', 'END'], 'w': []}, 'washer_operation_mode': {'type': 'enum', 'r': [], 'w': ['START', 'STOP', 'POWER_OFF', 'WAKE_UP']}, 'remote_control_enabled': {'type': 'boolean', 'r': True, 'w': False}, 'remain_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'relative_minute_to_stop': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'total_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'relative_hour_to_stop': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {'max': 30, 'min': 0, 'step': 1, 'except': []}}, 'total_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'remain_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'detergent_setting': {'type': 'string', 'r': ['NORMAL'], 'w': []}, 
                                                                                                                               'error': {'type': 'enum', 'r': ['TEMPERATURE_SENSOR_ERROR', 'DOOR_OPEN_ERROR', 'WATER_DRAIN_ERROR', 'UNABLE_TO_LOCK_ERROR', 'OVERFILL_ERROR', 'OUT_OF_BALANCE_ERROR', 'WATER_SUPPLY_ERROR', 'WATER_LEVEL_SENSOR_ERROR', 'LOCKED_MOTOR_ERROR']}}, 'mini': {'current_state': {'type': 'enum', 'r': ['DISPLAY_LOADSIZE', 'DRYING', 'REFRESHING', 'INITIAL', 'SPINNING', 'PROOFING', 'RUNNING', 'RESERVED', 'COOL_DOWN', 'PAUSE', 'POWER_OFF', 'STEAM_SOFTENING', 'RINSE_HOLD', 'CHANGE_CONDITION', 'ERROR', 'CHECKING_TURBIDITY', 'DETERGENT_AMOUNT', 'DETECTING', 'SLEEP', 'DISPENSING', 'RINSING', 'SOFTENING', 'FIRMWARE', 'PREWASH', 'END'], 'w': []}, 'washer_operation_mode': {'type': 'enum', 'r': [], 'w': ['START', 'STOP', 'POWER_OFF']}, 'remote_control_enabled': {'type': 'boolean', 'r': True, 'w': False}, 'total_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'remain_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'total_hour': {'type': 'range', 'r': {'max': 30, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 'remain_minute': {'type': 'range', 'r': {'max': 59, 'min': 0, 'step': 1, 'except': []}, 'w': {}}, 
                                                                                                                                                                                                                                                                                                                                                                                         'error': {'type': 'enum', 'r': ['TEMPERATURE_SENSOR_ERROR', 'DOOR_OPEN_ERROR', 'WATER_DRAIN_ERROR', 'UNABLE_TO_LOCK_ERROR', 'OVERFILL_ERROR', 'OUT_OF_BALANCE_ERROR', 'WATER_SUPPLY_ERROR', 'WATER_LEVEL_SENSOR_ERROR', 'LOCKED_MOTOR_ERROR']}}}

diff = DeepDiff(device_property_map, compare_property_map, ignore_order=True)

if diff:
    print("Different")
    print(f"{diff=}")
else:
    print("Same")