
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-29T21:16:05-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "dde652d430e57df1b338a46e9c279ac9e6c15071",
 "version": "1.32.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
