from pysaal.enums import Classification

DEFAULT_SATELLITE_DESIGNATOR = "INTL DES"
DEFAULT_SATELLITE_NAME = "DEFAULT NAME"
DEFAULT_AGOM = 0.03
DEFAULT_B_TERM = 0.01
DEFAULT_CLASSIFICATION = Classification.UNCLASSIFIED
