# coding: utf-8

"""
    Computebench Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.tool_executions_controller_get_tool_executions200_response import ToolExecutionsControllerGetToolExecutions200Response

class TestToolExecutionsControllerGetToolExecutions200Response(unittest.TestCase):
    """ToolExecutionsControllerGetToolExecutions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolExecutionsControllerGetToolExecutions200Response:
        """Test ToolExecutionsControllerGetToolExecutions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolExecutionsControllerGetToolExecutions200Response`
        """
        model = ToolExecutionsControllerGetToolExecutions200Response()
        if include_optional:
            return ToolExecutionsControllerGetToolExecutions200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.delete_tool_execution_controller_delete_tool_execution_200_response_data.DeleteToolExecutionController_deleteToolExecution_200_response_data(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.attributes.attributes(), )
                    ]
            )
        else:
            return ToolExecutionsControllerGetToolExecutions200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.delete_tool_execution_controller_delete_tool_execution_200_response_data.DeleteToolExecutionController_deleteToolExecution_200_response_data(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.attributes.attributes(), )
                    ],
        )
        """

    def testToolExecutionsControllerGetToolExecutions200Response(self):
        """Test ToolExecutionsControllerGetToolExecutions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
