
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-29T17:27:46-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "02ee4345604539ef5d4f8a0f89e0997a218f04f2",
 "version": "3.1.15.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
