# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.create_adjustment_note_equivalent_document_request_delivery_address import CreateAdjustmentNoteEquivalentDocumentRequestDeliveryAddress
from openapi_client.models.create_adjustment_note_equivalent_document_request_delivery_delivery_company import CreateAdjustmentNoteEquivalentDocumentRequestDeliveryDeliveryCompany
from typing import Optional, Set
from typing_extensions import Self

class CreateAdjustmentNoteEquivalentDocumentRequestDelivery(BaseModel):
    """
    Información acerca del envío y la compañía encargada
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, description="Fecha de la entrega", alias="date")
    time: Optional[StrictStr] = Field(default=None, description="Hora de la entrega")
    address: Optional[CreateAdjustmentNoteEquivalentDocumentRequestDeliveryAddress] = None
    delivery_company: Optional[CreateAdjustmentNoteEquivalentDocumentRequestDeliveryDeliveryCompany] = Field(default=None, alias="deliveryCompany")
    __properties: ClassVar[List[str]] = ["date", "time", "address", "deliveryCompany"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAdjustmentNoteEquivalentDocumentRequestDelivery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of delivery_company
        if self.delivery_company:
            _dict['deliveryCompany'] = self.delivery_company.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAdjustmentNoteEquivalentDocumentRequestDelivery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "time": obj.get("time"),
            "address": CreateAdjustmentNoteEquivalentDocumentRequestDeliveryAddress.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "deliveryCompany": CreateAdjustmentNoteEquivalentDocumentRequestDeliveryDeliveryCompany.from_dict(obj["deliveryCompany"]) if obj.get("deliveryCompany") is not None else None
        })
        return _obj


