from _typeshed import Incomplete

class GPT:
    client: Incomplete
    thread: Incomplete
    def __init__(self, api_key) -> None: ...
    def set_assistant_id(self, id) -> None: ...
    def new_chat_and_run(self, prompt: Incomplete | None = None): ...
