# Form implementation generated from reading ui file '/tmp/tmpx7k5ki78/jdProcessFileWatcher-2.0/jdProcessFileWatcher/ui/RunProgramDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RunProgramDialog(object):
    def setupUi(self, RunProgramDialog):
        RunProgramDialog.setObjectName("RunProgramDialog")
        RunProgramDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(RunProgramDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=RunProgramDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.category_list = QtWidgets.QListWidget(parent=RunProgramDialog)
        self.category_list.setObjectName("category_list")
        self.horizontalLayout.addWidget(self.category_list)
        self.entry_list = QtWidgets.QListWidget(parent=RunProgramDialog)
        self.entry_list.setObjectName("entry_list")
        self.horizontalLayout.addWidget(self.entry_list)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_box = QtWidgets.QDialogButtonBox(parent=RunProgramDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(RunProgramDialog)
        self.button_box.rejected.connect(RunProgramDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RunProgramDialog)

    def retranslateUi(self, RunProgramDialog):
        _translate = QtCore.QCoreApplication.translate
        RunProgramDialog.setWindowTitle(_translate("RunProgramDialog", "Run Programm"))
        self.label.setText(_translate("RunProgramDialog", "Select a Programm to run"))
