# string constants for CBR

COOKIE_NAME__CBR__SESSION_ID__ACTIVE  = 'CBR__SESSION_ID__ACTIVE'
COOKIE_NAME__CBR__SESSION_ID__USER    = 'CBR__SESSION_ID__USER'
COOKIE_NAME__CBR__SESSION_ID__PERSONA = 'CBR__SESSION_ID__PERSONA'
HEADER_NAME__CBR__SESSION_ID__USER    = 'cbr-session-id-user'
HEADER_NAME__CBR__SESSION_ID__PERSONA = 'cbr-session-id-persona'