
class  Uint8(int): ...
class Uint16(int): ...
class Uint32(int): ...
class Uint64(int): ...

class  Int8(int): ...
class Int16(int): ...
class Int32(int): ...
class Int64(int): ...

class Float32(float): ...
class Float64(float): ...
