# coding: utf-8

"""
    Thena Platform

    The Thena Platform API description  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages

NAME = "thena-platform-client"  # More descriptive name
VERSION = "1.0.0"
DESCRIPTION = "Python client for the Thena Platform API"
LONG_DESCRIPTION = open('README.md').read()

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=14.05.14",
    "six>=1.10",
    "python-dateutil>=2.5.3",
    "setuptools>=21.0.0",
    "urllib3>=1.15.1"
]

setup(
    name=NAME,
    version=VERSION,
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    author="Thena",
    author_email="support@thena.com",
    url="https://github.com/thena-ai/thena-platform-client",
    keywords=["API", "Thena Platform", "Client"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
    python_requires=">=3.6"
)
