# coding: utf-8

"""
    MyFolder

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uipath-it-pro-dev-my-folder.api.buckets_api import BucketsApi


class TestBucketsApi(unittest.TestCase):
    """BucketsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BucketsApi()

    def tearDown(self) -> None:
        pass

    def test_get_buckets_my_bucket(self) -> None:
        """Test case for get_buckets_my_bucket

        MyBucket
        """
        pass


if __name__ == '__main__':
    unittest.main()
