from .collection import view as collection
from .home import view as home
from .field import view as field
from .content import view as content
from .asset import view as asset
from .auth.auth import view as auth
from .user import view as user
from .api import view as api
from .access import view as access
