import logging
import uuid
from typing import Any

class RsLoggerAdapter(logging.LoggerAdapter):
    flow_id: uuid.UUID
    def __init__(self, logger: logging.Logger, extra: dict[str, Any] | None = None) -> None: ...
    def process(self, msg: Any, kwargs: dict[str, Any]) -> tuple[Any, dict[str, Any]]: ...

class AppLoggerAdapter(RsLoggerAdapter): ...

class HttpLoggerAdapter(AppLoggerAdapter):
    def request(self, url: str, method: str, *args: Any, **kwargs: Any) -> Any: ...
    def response(self, code: int, *args: Any, **kwargs: Any) -> Any: ...
