def has_requirement(requirements: str, serialized_security_policy: str, serialized_user_attributes: str) -> bool: ...
def security_policy_is_valid(serialized_security_policy: str) -> bool: ...
def user_attributes_is_valid(serialized_user_attributes: str) -> bool: ...
