# coding: utf-8

"""
    API Alegra Proveedor Electrónico Colombia

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.send_email_post200_response_data_company import SendEmailPost200ResponseDataCompany
from openapi_client.models.send_email_post200_response_data_document import SendEmailPost200ResponseDataDocument
from openapi_client.models.send_email_post200_response_data_receiver import SendEmailPost200ResponseDataReceiver
from typing import Optional, Set
from typing_extensions import Self

class SendEmailPost200ResponseData(BaseModel):
    """
    SendEmailPost200ResponseData
    """ # noqa: E501
    company: Optional[SendEmailPost200ResponseDataCompany] = None
    receiver: Optional[SendEmailPost200ResponseDataReceiver] = None
    document: Optional[SendEmailPost200ResponseDataDocument] = None
    attached_documents: Optional[StrictStr] = Field(default=None, description="Mensaje que indica que un archivo adjunto fue agregado", alias="attachedDocuments")
    __properties: ClassVar[List[str]] = ["company", "receiver", "document", "attachedDocuments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendEmailPost200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        # override the default output from pydantic by calling `to_dict()` of receiver
        if self.receiver:
            _dict['receiver'] = self.receiver.to_dict()
        # override the default output from pydantic by calling `to_dict()` of document
        if self.document:
            _dict['document'] = self.document.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendEmailPost200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "company": SendEmailPost200ResponseDataCompany.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "receiver": SendEmailPost200ResponseDataReceiver.from_dict(obj["receiver"]) if obj.get("receiver") is not None else None,
            "document": SendEmailPost200ResponseDataDocument.from_dict(obj["document"]) if obj.get("document") is not None else None,
            "attachedDocuments": obj.get("attachedDocuments")
        })
        return _obj


