import typing
import collections.abc
import typing_extensions
import nodeitems_utils

class SortedNodeCategory(nodeitems_utils.NodeCategory): ...

class CompositorNodeCategory(SortedNodeCategory):
    @classmethod
    def poll(cls, context):
        """

        :param context:
        """

class ShaderNodeCategory(SortedNodeCategory):
    @classmethod
    def poll(cls, context):
        """

        :param context:
        """

class TextureNodeCategory(SortedNodeCategory):
    @classmethod
    def poll(cls, context):
        """

        :param context:
        """

def cycles_shader_nodes_poll(context): ...
def eevee_cycles_shader_nodes_poll(context): ...
def eevee_shader_nodes_poll(context): ...
def group_input_output_item_poll(context): ...
def group_tools_draw(_self, layout, _context): ...
def line_style_shader_nodes_poll(context): ...
def node_group_items(context): ...
def object_cycles_shader_nodes_poll(context): ...
def object_eevee_cycles_shader_nodes_poll(context): ...
def object_eevee_shader_nodes_poll(context): ...
def object_shader_nodes_poll(context): ...
def register(): ...
def unregister(): ...
def world_shader_nodes_poll(context): ...
