depends = ('ITKPyBase', 'ITKTransform', 'ITKRegistrationMethodsv4', 'ITKImageLabel', 'ITKImageGrid', 'ITKIOTransformBase', 'ITKIOImageBase', 'ITKDisplacementField', 'ITKCommon', 'ITKBinaryMathematicalMorphology', )
templates = (  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFISS2', True, 'itk::Image< signed short,2 >, itk::Image< float,2 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDISS2', True, 'itk::Image< signed short,2 >, itk::Image< float,2 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFIUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDIUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< float,2 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFIUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDIUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< float,2 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFIF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDIF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFID2', True, 'itk::Image< double,2 >, itk::Image< float,2 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDID2', True, 'itk::Image< double,2 >, itk::Image< float,2 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFISS3', True, 'itk::Image< signed short,3 >, itk::Image< float,3 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDISS3', True, 'itk::Image< signed short,3 >, itk::Image< float,3 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFIUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDIUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< float,3 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFIUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDIUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< float,3 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFIF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDIF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >, double'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateFID3', True, 'itk::Image< double,3 >, itk::Image< float,3 >, float'),
  ('ANTSGroupwiseBuildTemplate', 'itk::ANTSGroupwiseBuildTemplate', 'itkANTSGroupwiseBuildTemplateDID3', True, 'itk::Image< double,3 >, itk::Image< float,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUS2', True, 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFID2', True, 'itk::Image< double,2 >, itk::Image< double,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF2IUS2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF2IUS2', True, 'itk::Image< float,2 >, itk::Image< unsigned short,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF2ID2', True, 'itk::Image< float,2 >, itk::Image< double,2 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF2ID2', True, 'itk::Image< float,2 >, itk::Image< double,2 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUS3', True, 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFID3', True, 'itk::Image< double,3 >, itk::Image< double,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF3IUS3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF3IUS3', True, 'itk::Image< float,3 >, itk::Image< unsigned short,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF3ID3', True, 'itk::Image< float,3 >, itk::Image< double,3 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF3ID3', True, 'itk::Image< float,3 >, itk::Image< double,3 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFISS4', True, 'itk::Image< signed short,4 >, itk::Image< signed short,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUC4', True, 'itk::Image< unsigned char,4 >, itk::Image< unsigned char,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIUS4', True, 'itk::Image< unsigned short,4 >, itk::Image< unsigned short,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFID4', True, 'itk::Image< double,4 >, itk::Image< double,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF4ISS4', True, 'itk::Image< float,4 >, itk::Image< signed short,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF4ISS4', True, 'itk::Image< float,4 >, itk::Image< signed short,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF4IUC4', True, 'itk::Image< float,4 >, itk::Image< unsigned char,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF4IUC4', True, 'itk::Image< float,4 >, itk::Image< unsigned char,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF4IUS4', True, 'itk::Image< float,4 >, itk::Image< unsigned short,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF4IUS4', True, 'itk::Image< float,4 >, itk::Image< unsigned short,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF4IF4', True, 'itk::Image< float,4 >, itk::Image< float,4 >, float'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationDIF4ID4', True, 'itk::Image< float,4 >, itk::Image< double,4 >, double'),
  ('ANTSRegistration', 'itk::ANTSRegistration', 'itkANTSRegistrationFIF4ID4', True, 'itk::Image< float,4 >, itk::Image< double,4 >, float'),
)
factories = ()
