# coding: utf-8

"""
    Demo250128

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uipath-it-pro-dev-demo.models.vm_ops_get_vm_list_get_output import VmOpsGetVmListGetOutput

class TestVmOpsGetVmListGetOutput(unittest.TestCase):
    """VmOpsGetVmListGetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VmOpsGetVmListGetOutput:
        """Test VmOpsGetVmListGetOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VmOpsGetVmListGetOutput`
        """
        model = VmOpsGetVmListGetOutput()
        if include_optional:
            return VmOpsGetVmListGetOutput(
                vm_names = {
                    'key' : ''
                    },
                vm_power_states = {
                    'key' : ''
                    },
                vm_os_types = {
                    'key' : ''
                    },
                vm_count = 56
            )
        else:
            return VmOpsGetVmListGetOutput(
        )
        """

    def testVmOpsGetVmListGetOutput(self):
        """Test VmOpsGetVmListGetOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
