# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.30.232843'

RELEASE_GIT_HEAD = '03c3d705778c07739e0034b51490877cffdc0983'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.01.30.232843dev'
