# coding: utf-8

"""
    Enyday API

    API for Enyday energy services integration

    The version of the OpenAPI document: 1.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from enyday.models.submeter_detail import SubmeterDetail
from enyday.models.user_detail import UserDetail
from typing import Optional, Set
from typing_extensions import Self

class ConsumptionAddress(BaseModel):
    """
    ConsumptionAddress
    """ # noqa: E501
    submeters: Optional[List[SubmeterDetail]] = None
    address_id: Optional[StrictInt] = None
    address: Optional[StrictStr] = None
    address_floor: Optional[StrictStr] = None
    address_side: Optional[StrictStr] = None
    door_number: Optional[StrictInt] = None
    total_doors_on_floor: Optional[StrictInt] = None
    building_id: Optional[StrictInt] = None
    power: Optional[Union[StrictFloat, StrictInt]] = None
    power_internal: Optional[Union[StrictFloat, StrictInt]] = None
    power_external: Optional[Union[StrictFloat, StrictInt]] = None
    price_internal: Optional[Union[StrictFloat, StrictInt]] = None
    price_external: Optional[Union[StrictFloat, StrictInt]] = None
    users: Optional[List[UserDetail]] = None
    user_name: Optional[StrictStr] = None
    consumption_total: Optional[Union[StrictFloat, StrictInt]] = None
    internal_percentage: Optional[Union[StrictFloat, StrictInt]] = None
    width: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["submeters", "address_id", "address", "address_floor", "address_side", "door_number", "total_doors_on_floor", "building_id", "power", "power_internal", "power_external", "price_internal", "price_external", "users", "user_name", "consumption_total", "internal_percentage", "width"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConsumptionAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in submeters (list)
        _items = []
        if self.submeters:
            for _item_submeters in self.submeters:
                if _item_submeters:
                    _items.append(_item_submeters.to_dict())
            _dict['submeters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        # set to None if building_id (nullable) is None
        # and model_fields_set contains the field
        if self.building_id is None and "building_id" in self.model_fields_set:
            _dict['building_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConsumptionAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "submeters": [SubmeterDetail.from_dict(_item) for _item in obj["submeters"]] if obj.get("submeters") is not None else None,
            "address_id": obj.get("address_id"),
            "address": obj.get("address"),
            "address_floor": obj.get("address_floor"),
            "address_side": obj.get("address_side"),
            "door_number": obj.get("door_number"),
            "total_doors_on_floor": obj.get("total_doors_on_floor"),
            "building_id": obj.get("building_id"),
            "power": obj.get("power"),
            "power_internal": obj.get("power_internal"),
            "power_external": obj.get("power_external"),
            "price_internal": obj.get("price_internal"),
            "price_external": obj.get("price_external"),
            "users": [UserDetail.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None,
            "user_name": obj.get("user_name"),
            "consumption_total": obj.get("consumption_total"),
            "internal_percentage": obj.get("internal_percentage"),
            "width": obj.get("width")
        })
        return _obj


