from _typeshed import Incomplete
from typing import Any

__all__ = ['noop', 'NoOpCls']

class NoOpCls:
    level: Incomplete
    def __init__(self, level: int = 0) -> None: ...
    def __getattr__(self, attr: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getitem__(self, item: Any) -> Any: ...
    def __enter__(self) -> Any: ...

def noop() -> NoOpCls: ...
